version: "3.4"

services:
  django:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: ./runserver.sh
    ports:
      - 8000:8000
    links:
      - mongodb
    volumes:
      - ./src:/src
    environment:
      - PYTHONUNBUFFERED=True
      - MONGO_USERNAME=dev
      - MONGO_PASSWORD=dev
      - MONGO_DATABASE=botflowapi
      - MONGO_AUTHENTICATION_DATABASE=admin
      - MONGO_HOST=mongodb
  mongodb:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=dev
      - MONGO_INITDB_DATABASE=botflowapi
    ports:
      - 27017:27017
