version: "3.4"

services:
  node-server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: node
    restart: unless-stopped
    ports:
      - 3030:3030
    links:
      - mongodb
    volumes:
      - ./server/:/usr/app/server/
      - /server/node_modules
    environment:
      - MONGO_USERNAME=dev
      - MONGO_PASSWORD=dev
      - MONGO_DATABASE=rasa-nlu
      - URL_GITHUB_IO=teste.com
  mongodb:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=dev
      - MONGO_INITDB_DATABASE=rasa-nlu
    ports:
      - 27017:27017
